### ISSUE TITLE
Battlefield Scene

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/ITP-Game-4AHITN#38]
## Planned outcome:
A scene in unity containing the terrain on which the battle between players and zombies will take place (the game itself).

## Tasks:
- [x] Create a new Scene "Battlefield"
- [x] Make a terrain 
- [x] Modify the terrain so that it isn't completely flat
- [x] Add mountains on the borders
- [x] Add grass and other textures
- [x] Add some walls and rocks
- [x] Create a huge forest
- [x] Add pathways
- [ ] #42
- [x] Additions that can be added later:
  - [x] Lots of fog so that zombies can't be seen spawning
  - [x] Other details that improve the look (flowers, bushes...)

## Notes:
https://youtu.be/99IecSRWA5Y?si=pJ1CG9f9fb7Ab5vP
https://www.youtube.com/watch?v=sMNY980h5t8
https://www.youtube.com/watch?v=eD2Ojp98UK4
https://www.youtube.com/watch?v=9SXxAc3mlDY
https://www.youtube.com/watch?v=pZuXDZkBMow
https://youtu.be/qV9YaRXupK8?si=rXlDiksVo01OnlYi
