### ISSUE TITLE
Starting a multiplayer game

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/ITP-Game-4AHITN#49]
## Planned outcome:
After all players in a lobby are ready, and the host presses the start button, a NetCode connection is established between the players where the host of the lobby also hosts the game. The rest of the players connect to the host as clients and the game scene loads for all players. If a game has been started, players should still be able to join the lobby if it is not full. In that case, they immediately load the game scene.

## Tasks:
- [x] Add a property to each lobby that stores the current state of the lobby: Waiting, Starting or Started
- [x] When the host presses on Start, check if all players are ready
- [x] If yes, Update the state of the lobby to Starting
- [x] Start the host on the NetworkManager.Singleton
- [x] After starting the host, check if the host is the only player in the lobby
- [x] If yes, simply load the game scene
- [x] If not, subscribe to the OnClientConnectedCallback event on the NetworkManager
- [x] When a new client has connected, check if all clients from the lobby have connected
- [x] If yes, load the Game scene over the NetworkManager.Singleton.SceneManager
- [x] Subscribe to the OnLoadEventCompleted event and update the lobby state to Started in the event handler
- [x] In the LobbyManager, in OnJoinedLobbyChanged, check if the state is Starting or Started
- [x] If yes, and this instance has not been connected yet, start a client on the NetworkManager
