### ISSUE TITLE
Map client ids to lobby players

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/ITP-Game-4AHITN#51]
## Planned outcome:
In order to get the nickname or other data from connected clients, their ids (on the NetworkManager) need to be mapped to their player in the lobby.

## Tasks:
- [x] Create a struct that will map a client id to a lobby player id
- [x] Create a `NetworkList `of the struct above to store all the players (This can be done in the `GameManager`)
- [x] Implement `INetworkSerializable` in the created struct in order to be able to create a `NetworkList` of that type
- [x] Make sure to use `FixedString64Bytes` instead of `string` as the date type of the player id
- [x] In `OnNetworkSpawn` on the `GameManager` (which will run on each client once they're connected), call a Server RPC and pass the local client id and the local lobby player id
- [x] In the Server RPC method, just add the pair to the `NetworkList`
- [x] Subscribe to `OnClientDisconnectCallback` in the `NetworkManager` and in the handler, if it's the host, remove the mapping of the client that has disconnected
- [x] Kick the client from the lobby that has disconnected
