### ISSUE TITLE
Spawn players when they join the game

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/ITP-Game-4AHITN#52]
## Planned outcome:
When a game has started, a player object (currently just a capsule) should be spawned for them. If a client joins later, a player object should also be spawned.

## Tasks:
- [x] Add the `NetworkObject` component to the player prefab
- [x] Create a method that spawns a player with the client id passed as a parameter
- [x] Make sure this method is only called on the server
- [x] In this method, first call `Instantiate` to spawn the player prefab
- [x] Then get the `NetworkObject` component from it and call `SpawnAsPlayerObject()` and pass the client id
- [x] In `OnNetworkSpawn` in the `GameManager`, listen to `OnLoadEventCompleted`
- [x] In the listener, for each connected client, call the implemented method for spawning a player
- [x] Subscribe to `OnClientConnectedCallback` where a player is spawned for that connected client
