### ISSUE TITLE
Synchronize player movement

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/ITP-Game-4AHITN#53]
## Planned outcome:
Each client owns one player and only that player moves when the appropriate keys are pressed on the corresponding client. When a player moves, it does so on all clients (the positions of all clients are synchronised).

## Tasks:
- [x] Implement the [ClientNetworkTransform](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/blob/main/Packages/com.unity.multiplayer.samples.coop/Utilities/Net/ClientAuthority/ClientNetworkTransform.cs) and add that component to the player prefab
- [x] Untick syncing for rotation on the X and Z Axes and scale on all axes
- [x] Make the `PlayerController` inherit from `NetworkBehaviour`
- [x] In `Update`, don't do anything unless `IsOwner` is true
- [x] #54

## Notes:
All players exist on all clients, obviously. But that also means that multiple `PlayerController` components exist on one client so when a client presses 'W', for instance, all players in the game would move. To prevent this, we simply check on each player if that is the player owned by the local client that pressed 'W', and only if that is the case, we move that player.
