### ISSUE TITLE
Make the camera follow only the player owned by the local client

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/ITP-Game-4AHITN#54]
## Planned outcome:
Every client owns one player object. Since the game is first person, the camera for each client should follow the player that the corresponding client owns.

## Tasks:
- [x] Create a new Script and attach it to the main camera in the game scene
- [x] In this script, create a variable that will store the `Transform` which the camera will follow
- [x] In `LateUpdate` check if the transform to follow is not null
- [x] if not null, set the position of the camera to the position of the transform + some offset
- [x] Test what the offset should be for the first person view to look good
- [x] In `PlayerController` in `OnNetworkSpawn`, check if that player is owned by the local client
- [x] If yes, get the created component from `Camera.main` and assign the transform to follow to this player

## Notes:
Recommended offset for the camera: X: 0, Y: 0.5 - 0.75, Z: 0
