### ISSUE TITLE
Disable all interactions while loading

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/ITP-Game-4AHITN#55]
## Planned outcome:
While loading something (logging in, creating a lobby...), the user shouldn't be able to click on something else. This solves a lot of bugs that can happen due to spamming buttons while requests are still being processed.

## Tasks:
- [x] Create a loading screen that covers the entire canvas
- [x] Make it a singleton accessible from everywhere
- [x] Use the implemented `TextAnimator` for nicer appearance
- [x] Add it onto a game object in the first scene and call `DontDestroyOnLoad` in the `Awake` method
- [x] Implement public methods to show and hide the loading screen

## Notes:
Calling the `DontDestroyOnLoad` method makes sure that the loading screen doesn't get destroyed when the game switches to another scene
