### ISSUE TITLE
Refactor the popup box

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/ITP-Game-4AHITN#56]
## Planned outcome:
Users shouldn't be able to click on anything when a popup box is shown. Also, for showing a popup, there is no need to instantiate a prefab each time and assign it the current main canvas. Rather, the same pattern should be used as with the loading screen in #55 

## Tasks:
- [x] To disable all interactions while a popup is shown, add a panel to the popup box that covers the entire screen
- [x] Make the panel transparent
- [x] Follow the singleton pattern as described in #55 
- [x] Apply the changes in the rest of the project
