### ISSUE TITLE
Color the player prefab in what was chosen in the lobby

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/ITP-Game-4AHITN#57]
## Planned outcome:
Each player can choose a color in the lobby. The player prefab in the game (currently just a capsule) should be colored in this in order to differentiate each player.

## Tasks:
- [x] Create a script `GamePlayer` and attach it to the player prefab. This script will be the class that will represent a player in the game
- [x] Make the script a `NetworkBehaviour`
- [x] Create a `NetworkVariable<FixedString32Bytes>` that will store the color of the corresponding player in hexadecimal
- [x] Subscribe to the `OnValueChanged` event of the network variable
- [x] In the event handler, and in `Awake`, convert the hex value into a color with `ColorUtility.TryParseHtmlString` and assign it to the material of the capsule
- [x] In the `GameManager` in `SpawnPlayer`, get the lobby player of that client and get the color in hex from the Data property
- [x] Get the `GamePlayer` from the spawned client and assign the network variable the color
