### ISSUE TITLE
Display player names in the game

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/ITP-Game-4AHITN#58]
## Planned outcome:
Above each player prefab (currently a capsule), the name of the player that owns that player should be displayed in order to differentiate the players even more easily.

## Tasks:
- [x] Add a canvas to the player prefab and set it to World Space 
- [x] Add a Text to the Canvas and customize it (this will contain the player's name)
- [x] Position the canvas above the capsule
- [x] Create a new script `LookAtCamera` and attach it to the canvas (this script will ensure each player's name will look at the camera so that it can be read easily)
- [x] In this script, in `LateUpdate`, just set `transform.forward = _camera.transform.forward`
- [x] Implement a `NetworkVariable<FixedString32Bytes>` in `GamePlayer` that will store the nickname of that player
- [x] Follow the same rest of the steps as described in #57
