### ISSUE TITLE
Refactor the ready-mechanism for lobbies

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/ITP-Game-4AHITN#59]
## Planned outcome:
Instead of the host only being able to start the game when all players in the lobby are ready, they should now be able to start the game at all times. The rest of the players in the lobby will stay in the lobby if they are not ready and when they are ready, they will just join the game.

## Tasks:
- [x] Do not check whether all players are ready when the Start button is clicked
- [x] When the Ready button is clicked, check if the lobby state is `Starting` or `Started`
- [x] If yes, call `TryConnectToGame()` in the `LobbyManager`
