### ISSUE TITLE
Integrate with Relay

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/ITP-Game-4AHITN#62]
## Planned outcome:
Player movement is now synchronized over the network, not just on the local machine

## Tasks:
- [x] Install the Relay Package in the Package Manager
- [x] Allocate the Relay before starting the game by accessing the singleton of `RelayService`
- [x] Get the allocation created
- [x] Set the Relay Server Data on the `NetworkManager` by getting the `UnityTransport` component
- [x] For the connection type, use the recommended type which is `dtls`
- [x] Store the join code of the relay in the lobby data
- [x] Before joining the game with a player, join the relay by accessing the lobby data for the code
- [x] Catch exceptions when calling methods that use Unity Gaming Services

## Notes:
https://www.youtube.com/watch?v=7glCsF9fv3s&t=20130s
