### ISSUE TITLE
Refactor UI to one Scene

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/ITP-Game-4AHITN#69]
## Planned outcome:
All menus (main menu, login, sign up, lobby) should all be in one scene rather than split up into different scenes in order to allow transitioning between those menus with animations. The menus can then be switched between by setting one of them to active and deactivating others. A menu should be its own GameObject with the actual content of the menu being added to that GameObject as a child.

## Tasks:
- [x] Create a "Menu" scene
- [x] #70
- [x] #71
- [x] Add a transition between login and sign up
- [x] Add an entering and exiting animation for login and sign up menus
- [x] #72
- [x] Add an entering animation for the main menu
- [x] #73
- [x] #74
- [x] #75
- [x] Add an exiting animation for the main menu
- [x] Add an entering animation for the lobby menu
- [x] Add an exiting animation for the lobby menu
- [x] When joining a game, fade the menu to black, and then in the game, fade the game back in

## Notes:
For adding rounded corners to UI elements: https://www.youtube.com/watch?v=gO4jnaxvMjk
For switching between input fields with TAB: https://www.youtube.com/watch?v=PIA-4BUJfo0
> [!TIP]
> Use the LeanTween asset from the asset store to animate the UI
> https://www.youtube.com/watch?v=Ll3yujn9GVQ
> [!TIP]
> Here are some colors for dark mode (Source: Modrinth desktop app):
> Base background: #17191c
> Section background: #27292e
> Element background on hover: #212228
> Element background: #434956
> Disabled element background: #36393f
> Base foreground: #a6aebb
> Highlighted foreground: #edf8fb
> Dark foreground: #010702
> Green background: #19be5d

**Comment by DarioLoll** [comment]
- [ ] Refactor the animation with using LeanTween instead of Animators
