### ISSUE TITLE
User Registration With Playfab

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/ITP-Game-4AHITN#76]
## Planned outcome:
Players can register an account by entering their E-Mail Address, a unique username, and a password (two times). When they do that, a request should be sent to PlayFab. After a successful registration, the player should be prompted to verify the E-Mail address by clicking on the link sent to their E-Mail. After a successful verification, the player should enter their desired Display Name.

## Tasks:
- [x] #71
- [x] Install the PlayFab unity package
- [x] Install the PlayFab SDK
- [x] Add an on click event to the sign up button
- [x] In the event handler, check if all input fields are filled out
- [x] Check if the entered email and username are valid (alphanumerical)
- [x] Check if the password is valid (confirmed, and contains at least 8 characters)
- [x] If everything is alright, send a request to the PlayFab server via the Client API to register the user
- [x] After a successful registration, update the user's contact E-Mail to the same E-Mail they registered with
- [x] Also switch to a panel where the user is told to verify their E-Mail and provide a button to resend the verification every 30s
- [x] In the PlayFab dashboard, add an E-Mail template for the verification (include the variable mentioned in playfab docs for the link)
- [x] In the PlayFab dashboard, add an action that is triggered when a player updates their E-Mail
- [x] For this action, select "Send E-Mail" and choose the template 
- [x] Install the SMTP addon on the PlayFab dashboard
- [x] Set up google SMTP server 

## Notes:
https://www.youtube.com/watch?v=2hPSReq1or0&list=PLVGTm2ujeFKQzvpbS3UnDvQviUN0dk-iF&pp=iAQB
