### ISSUE TITLE
User Login with PlayFab

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/ITP-Game-4AHITN#77]
## Planned outcome:
After registering and verifying their E-Mail, players should always be able to log back in into that account their registered with the appropriate username and password. Players should also be able to request to reset their password by receiving a recovery mail from PlayFab. Alternatively, players should be able to play as a guest, in which case they just need to enter a Display Name.

## Tasks:
- [x] #76 
- [x] Add an on click event to the login button
- [x] In the event handler, check if all input fields are filled out
- [x] If yes, send the request to the PlayFab server
- [x] If successful, switch to the a menu where the player can choose their display name
- [x] Add a "Forgot Password" button to the Login menu
- [x] Add an on click event to the Forgot Password button
- [x] In the event handler, send a recovery email with the PlayFab Client API
- [x] Add a button to the login menu "Continue as Guest"
- [x] If clicked, switch to a panel where the player is asked to just enter their display name of choice
- [x] After setting the display name, load the main menu
- [x] If the user has already chosen a display name (e.g. is logging in for the second time), don't load the menu for setting the display name

## Notes:
https://www.youtube.com/watch?v=2hPSReq1or0&list=PLVGTm2ujeFKQzvpbS3UnDvQviUN0dk-iF&pp=iAQB
