### ISSUE TITLE
Add an option to edit the player's profile

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/ITP-Game-4AHITN#81]
## Planned outcome:
Players should be able to change their display name once their logged in.
Also, players who initially logged in as a guest would lose their account if they lose their device. In case they want to save the progress on their guest account, they should be able to do that by linking it to an ordinary playfab account.
Also, add an option to request a password reset in the profile settings.

## Tasks:
- [x] Add a button in the main menu that opens up the profile settings
- [x] Create a canvas for editing the profile
- [x] Add an input field where the player can enter their new display name
- [x] Add a save button which saves the change the player made to the display name
- [x] Check if the player is logged in as a guest
- [x] If yes, display a button to link their account
- [x] If not, display a button to request a password reset
- [x] When the reset password button is clicked, send an account recovery email to the player via PlayFab
- [x] When the link account button is clicked, switch to the Sign Up menu
- [x] When the user enters the information, send a verification link to the entered email
- [x] After confirming the email, switch to the menu where the player can add a username and password to their account

## Notes:
https://learn.microsoft.com/en-us/rest/api/playfab/client/account-management/add-username-password?view=playfab-rest
https://learn.microsoft.com/en-us/rest/api/playfab/client/account-management/link-custom-id?view=playfab-rest
https://learn.microsoft.com/en-us/rest/api/playfab/client/account-management/send-account-recovery-email?view=playfab-rest
