### ISSUE TITLE
Refactor the sign up process

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/ITP-Game-4AHITN#82]
## Planned outcome:
Currently, when players sign up, a playfab account with the entered email, username and password is created before the email has even been confirmed. This way, players can create accounts with whatever emails then want. They can't log into those accounts without verifying the email, but they shouldn't be able to create the account then in the first place. Instead, on the sign up menu, players should only enter their email address, and then be prompted to add a username and password after verifying the email.

## Tasks:
- [x] Split the sign up canvas into two: One containing just the email and the button to switch the login, and the other containing the options to add a username, a password, and a field to confirm the password.
- [x] When the game starts, always initially log in the player as a guest
- [x] When the player enters the email to sign up, update the contact email of the guest account, which will send them a verification link
- [x] Provide a button to continue which checks if the email has been verified
- [x] If the email has been verified when the button is clicked, switch to the second sign up menu
- [x] On the second sign up menu, when the user enters their information, add that to the guest account

## Notes:
https://learn.microsoft.com/en-us/rest/api/playfab/client/account-management/add-username-password?view=playfab-rest
https://learn.microsoft.com/en-us/rest/api/playfab/client/account-management?view=playfab-rest
https://community.playfab.com/idea/979/211818267-Checking-if-email-address-exisits.html
