### ISSUE TITLE
Log out option

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/ITP-Game-4AHITN#83]
## Planned outcome:
There is currently no way for a player to log out once they're logged in because they stay logged in. The player should be able to click on the profile settings in the main menu, and log out, in which case he is sent back to the login menu.

## Tasks:
- [ ] Add a log out button to the profile edit canvas
- [ ] When clicked, hide the main menu and load the login canvas
- [ ] Figure out how to end the session with playfab
