### ISSUE TITLE
Refactor the UI AGAIN!!!

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/ITP-Game-4AHITN#91]
## Planned outcome:
When switching between windows, the loading screen should come in-between. This means that the entire flow of the UI needs to be refactored 😩 
- For modal windows, there shouldn't be a loading screen that covers the entire modal window. Instead, a small loading indicator (the logo circling) should be displayed next to the button that was clicked and caused the loading
- For buttons that only cause a modal screen to appear, the same principle should be applied
- For things that don't take loading (things that aren't sending any requests over the network), there shouldn't be any loading screens
- For switching scenes, a loading screen should be displayed, and the scene should be loaded in the background (this currently applies to the Game scene)
- In order to prevent the user from breaking anything while something is loading, ignore all interactions or disable the buttons while loading
- For joining/creating/leaving a lobby, display a full loading screen

## Tasks:
- [x] Since the way of letting the player know something is loading depends on the window, each window should implement their own method for it. Add a DisplayLoading() method to `AnimatableWindow`.
- [x] By default, the `DisplayLoading()` method should display the entire loading screen, but it should be able to be overriden
- [x] To dynamically add the loading circle next to whatever button, create a prefab of a small loading circle, pack each button into a container with a horizontal layout group and then instantiate the loading circle under that container. 
- [x] For this, add a method in `AnimatableWindow` called `DisplayLoading(nextToButton : ButtonBase)` 
- [x] To prevent interactions while a request is being processed, add a boolean property in `AnimatableWindow` called `IsBusy` and then check if the window is busy in all interaction methods
- [x] Listen to the corresponding event from manager classes (`PlayFabManager`, `LobbyManager`) to know when to disable the loading and set `IsBusy` to false

## Notes:
PLAN BEFORE IMPLEMENTING!!!!
